tickers:
  LKOH:
    - LKOH
    - Лукойл
    - ЛУКОЙЛ
    - Лукойла
  SBER:
    - SBER
    - Сбер
    - Сбера
    - Сбербанк
    - Сбербанка
  ROSN:
    - ROSN
    - Роснефть
    - Роснефти
    - Роснефтью
  GAZP:
    - GAZP
    - Газпром
    - Газпрома
  VTBR:
    - VTBR
    - ВТБ
  YDEX:
    - YDEX
    - Яндекс
    - Яндекса
    - Яндексу
    - Яндексе
    - Yandex
  PLZL:
    - PLZL
    - Полюс
    - Полюса
  T:
    - Т-Технологии
    - Т-Технологий
    - Т-Банк
    - Т-Банка
    - ТБанк
    - ТБанка
    - Тинькофф
    - TCS
  NVTK:
    - NVTK
    - Новатэк
    - НОВАТЭК
    - Новатэка
  X5:
    - X5
    - X5 Group
    - ИКС 5
    - Пятёрочка
    - Перекрёсток
  GMKN:
    - GMKN
    - Норникель
    - Норникеля
    - Норильский никель
  MGNT:
    - MGNT
    - Магнит
    - Магнита
  ALRS:
    - ALRS
    - АЛРОСА
  AFLT:
    - AFLT
    - Аэрофлот
    - Аэрофлота
  CHMF:
    - CHMF
    - Северсталь
  NLMK:
    - NLMK
    - НЛМК
  MOEX:
    - MOEX
    - Московская биржа
    - Московской биржи
    - Мосбиржа
    - Мосбиржи
  SNGSP:
    - SNGSP
    - Сургутнефтегаз
    - Сургутнефтегаза
  MTSS:
    - MTSS
    - МТС
  PIKK:
    - PIKK
    - ГК ПИК
